resources/views/layouts/app.blade.php
=> test-sachiko commit

resources/views/layouts/app.blade.php
=> test commit Misa

resources/views/layouts/app.blade.php
=> test marin

app/Models/User.php, database/migrations/0001_01_01_000000_create_users_table.php, database/migrations/2024_08_07_123252_add_soft_deletes_at_users.php
Additions:
-Added 2024_08_07_123252_add_soft_deletes_at_users.php
Changes:
-0001_01_01_000000_create_users_table.php
-app/Models/User.php
=> [database/users/all] - add soft delete to users table

public/css/login.css, public/css/style.css, resources/views/auth/login.blade.php, resources/views/auth/register.blade.php
=> [UI/register/marin]

public/css/profile.css, public/css/style.css, public/js/profile.js, resources/views/layouts/app.blade.php, resources/views/profile/setting.blade.php
-added js that changes images when radio button checked
=> [UI/profile/marin]

app/Http/Controllers/Admin/QuotesController.php, app/Http/Controllers/BookmarkController.php, app/Models/Bookmark.php, app/Models/Quote.php, app/Providers/AppServiceProvider.php, database/migrations/2024_08_08_105201_create_quotes_table.php, database/migrations/2024_08_08_105424_create_add_soft_deletes_to_quotes.php, database/migrations/2024_08_14_122217_create_bookmarks_table.php, public/css/quote_style.css, resources/views/admin/quotes/index.blade.php, resources/views/admin/quotes/modals/action.blade.php, routes/web.php
create 
-Admin index
-create modal
-edit modal
-delete modal
=> create designs on Quote page

app/Http/Controllers/JournalController.php, app/Models/Journal.php, app/Models/Reply.php, app/Models/User.php, database/migrations/2024_08_07_132349_create_journals_table.php, database/migrations/2024_08_08_110952_add_soft_deletes_at_journals.php, database/migrations/2024_08_16_115148_create_replies_table.php, public/css/journal.css, resources/views/journals/contents/modals/add.blade.php, resources/views/journals/contents/modals/delete.blade.php, resources/views/journals/contents/modals/edit.blade.php, resources/views/journals/contents/modals/reply.blade.php, resources/views/journals/index.blade.php, routes/web.php
Additions:
-Added journal.php file
-Added journal page to routes
=> [Ul/journal] - journal page

public/css/style.css
-added some changes to style.css
=> [UI/home/marin]

resources/views/home.blade.php
-enable the links to journal and mood tracker pages
=> [backend/home/marin]

resources/views/components/footer.blade.php, resources/views/components/sidebar.blade.php
Changed the header parts
[ components/sidebar.blade.php ]
[ components/footer.blade.php ]
=> Changed the header parts

app/Http/Controllers/MoodController.php, app/Http/Controllers/ProfileController.php, app/Models/Mood.php, app/Models/User.php, database/migrations/2024_08_17_065443_create_moods_table.php, public/css/profile-show.css, public/js/profile.js, resources/views/auth/login.blade.php, resources/views/layouts/app.blade.php, resources/views/mood/login-first.blade.php, resources/views/mood/login.blade.php, resources/views/profile/setting.blade.php, resources/views/profile/show.blade.php, routes/web.php
=> [backend/profile/marin]

app/Http/Controllers/Admin/InquiriesController.php, app/Http/Controllers/InquiryController.php, app/Models/Inquiry.php, database/migrations/2024_08_16_113756_create_inquiries_table.php, public/css/contactus.css, public/js/inquiry.js, public/js/jquery.js, resources/views/admin/contactus/index.blade.php, resources/views/admin/contactus/modals/details.blade.php, resources/views/contactus/modals/inquiry.blade.php, resources/views/contactus/modals/submitcomplete.blade.php
create
-modal form for inquiry
-thank you modal page
=> create contact us modal for users

app/Http/Controllers/Admin/QuotesController.php, app/Models/User.php, package-lock.json, package.json, resources/views/admin/quotes/index.blade.php, resources/views/home.blade.php, resources/views/layouts/app.blade.php, resources/views/test/index.blade.php, routes/web.php, vite.config.js
=> create new contact us page

app/Http/Controllers/JournalController.php, database/migrations/2024_08_20_151451_update_foreign_keys_on_journals_table.php, resources/views/home.blade.php, resources/views/journals/contents/modals/add.blade.php, resources/views/journals/index.blade.php
=> [Ul/journal/sachiko_fixed] - journal fixed

app/Http/Controllers/Admin/InquiriesController.php, public/css/contactus.css, public/js/inquiry-modal.js, resources/views/admin/contactus/index.blade.php, resources/views/admin/contactus/modals/details.blade.php, resources/views/contactus/modals/inquiry.blade.php
=> I update modal inquiry page for admin

app/Http/Controllers/Admin/DeletionReasonController.php, app/Http/Controllers/Admin/UserController.php, public/css/deletion-reason.css, public/css/navbar.css, public/css/style-blue.css, public/css/style-dark.css, public/css/style-green.css, public/css/style-pink.css, public/css/style-yellow.css, public/css/style.css, public/css/users.css, public/js/deletion-reason.js, resources/views/admin/deletion-reasons/index.blade.php, resources/views/admin/users/index.blade.php, resources/views/layouts/app.blade.php, routes/web.php
-completed admin/user page
-enable to activate/deactivate users
=> Backend/admin users/marin

resources/views/layouts/app.blade.php, routes/web.php
-added switching theme color functionality
=> [backend/admin-users/marin]

public/css/navbar.css, resources/views/components/navbar-each.blade.php, resources/views/components/navbar-home-admin.blade.php, resources/views/components/navbar-home.blade.php, resources/views/components/navbar-users.blade.php
Fixed login button and avatar icon in navbars. Updated navbar.css.
=> Fixed navbars

resources/views/components/navbar-home-admin.blade.php, resources/views/components/navbar-home.blade.php, resources/views/dashboard.blade.php
Fiixed link of profile icon in 2 navbars.
Added logout button in dashborad page in case we lose our own way in this app.
=> Fixed & Added

public/css/journal.css, resources/views/journals/contents/modals/add.blade.php, resources/views/journals/contents/modals/comment.blade.php, resources/views/journals/contents/modals/delete.blade.php, resources/views/journals/contents/modals/edit.blade.php, resources/views/journals/contents/modals/reply.blade.php, resources/views/journals/index.blade.php
- Change the icon color depending on whether the like score is positive or negative
- Focus the input area when the modal is displayed
=> backend/journal  update javascript at journal

public/js/calendar.js, resources/views/admin/deletion-reasons/index.blade.php
=> [backend/mood/marin]

public/css/faq.css
=> I changed the size of FAQ.
